[build-system]
requires = [
    "setuptools>=39.1.0",
    "wheel",
    "robotframework>=3.1.2",
    "requests>=2.25.1",
    "jsonpath-ng>=1.4.3",
    "jsonschema>=3.2.0"
]
build-backend = "setuptools.build_meta"